#!/usr/bin/env python3
import argparse
import os
import subprocess
import sys
import matplotlib.pyplot as plt

# NOTE: AI-generated by Claude Sonnet 4.6, ain't no way I'm manually creating a plot script


CACHE_DIR = ".cache"
BINARY = "./generate_numbers"


def ensure_binary():
    if not os.path.isfile(BINARY):
        print(f"Error: binary '{BINARY}' not found. Build it first with:\n\n    make build\n", file=sys.stderr)
        sys.exit(1)


def ensure_cache_dir():
    os.makedirs(CACHE_DIR, exist_ok=True)


def generate_if_missing(number_type: str, n: int) -> str:
    filename = os.path.join(CACHE_DIR, f"{number_type}_{n}.txt")
    if not os.path.exists(filename):
        print(f"Generating {filename}...")
        result = subprocess.run(
            [BINARY, "-t", number_type, "-m", "list", "-n", str(n), "-o", filename],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            print(f"Error running {BINARY}: {result.stderr}", file=sys.stderr)
            sys.exit(1)
    else:
        print(f"Using cached {filename}")
    return filename


def read_numbers(filename: str) -> list[int]:
    with open(filename) as f:
        return [int(line.strip()) for line in f if line.strip()]


def build_cumulative_function(numbers: list[int], limit: int) -> tuple[list[int], list[int]]:
    """
    Returns (x_values, y_values) where y is the count of numbers <= x.
    We step through each integer from 0 to limit.
    """
    numbers_sorted = sorted(numbers)
    x_vals = list(range(0, limit + 1))
    y_vals = []
    count = 0
    idx = 0
    for x in x_vals:
        while idx < len(numbers_sorted) and numbers_sorted[idx] <= x:
            count += 1
            idx += 1
        y_vals.append(count)
    return x_vals, y_vals


def main():
    parser = argparse.ArgumentParser(
        description="Plot cumulative counts of Harshad and prime numbers up to 10^N."
    )
    parser.add_argument(
        "N",
        type=int,
        help="Generate numbers between 0 and 10^N",
    )
    args = parser.parse_args()
    n = args.N
    limit = 10 ** n
    ensure_binary()
    ensure_cache_dir()

    harshad_file = generate_if_missing("harshad", n)
    prime_file = generate_if_missing("prime", n)

    harshad_numbers = read_numbers(harshad_file)
    prime_numbers = read_numbers(prime_file)

    print(f"Building cumulative functions up to {limit:,}...")
    hx, hy = build_cumulative_function(harshad_numbers, limit)
    px, py = build_cumulative_function(prime_numbers, limit)

    fig, ax = plt.subplots(figsize=(10, 6))
    ax.plot(hx, hy, label="Harshad numbers", color="#e07b39", linewidth=1.5)
    ax.plot(px, py, label="Prime numbers", color="#4a90d9", linewidth=1.5)

    ax.set_ylabel("Count of numbers ≤ x")
    ax.set_xlabel("x")
    ax.set_title(f"Cumulative count of Harshad vs Prime numbers up to {10**n}")
    ax.legend()
    ax.grid(True, linestyle="--", alpha=0.4)
    fig.tight_layout()

    os.makedirs("plots", exist_ok=True)
    output_plot = os.path.join("plots", f"plot_{n}.png")
    plt.savefig(output_plot, dpi=150)
    print(f"Plot saved to {output_plot}")
    plt.show()


if __name__ == "__main__":
    main()